return {
  {
    "AstroNvim/astroui",
    ---@type AstroUIOpts
    -- opts = {
    --   scheme = "astrolight",
    -- },
  },
  -- {
  --   "wuelnerdotexe/vim-enfocado",
  --   config = function(_, _)
  --     vim.o.termguicolors = true
  --     vim.o.background = "dark"
  --     vim.cmd.colorscheme "enfocado"
  --     vim.cmd[[hi! link MiniStatuslineFilename MoreMsg]]
  --     vim.cmd[[hi! link TabLineSel MoreMsg]]
  --     vim.cmd[[hi! link TabLine LspInlayHint]]
  --   end,
  -- },
  -- {
  --   "bluz71/vim-moonfly-colors",
  --   name = "moonfly",
  --   lazy = false,
  --   priority = 1000,
  -- },
  -- {
  --   "zenbones-theme/zenbones.nvim",
  --   -- Optionally install Lush. Allows for more configuration or extending the colorscheme
  --   -- If you don't want to install lush, make sure to set g:zenbones_compat = 1
  --   -- In Vim, compat mode is turned on as Lush only works in Neovim.
  --   dependencies = "rktjmp/lush.nvim",
  --   lazy = false,
  --   priority = 1000,
  --   -- you can set set configuration options here
  --   config = function()
  --       -- vim.g.zenbones_darken_comments = 45
  --       vim.cmd.colorscheme('zenbones')
  --   end
  -- },
  -- {
  --   "maxmx03/solarized.nvim",
  --   lazy = false,
  --   priority = 1000,
  --   opts = {
  --     transparent = {
  --       enabled = true,
  --       pmenu = true,
  --       normal = false,
  --       normalfloat = true,
  --       neotree = false,
  --       nvimtree = false,
  --       whichkey = false,
  --       telescope = false,
  --       lazy = false,
  --     },
  --     on_highlights = nil,
  --     on_colors = nil,
  --     palette = "solarized", -- solarized (default) | selenized
  --     variant = "winter", -- "spring" | "summer" | "autumn" | "winter" (default)
  --     error_lens = {
  --       text = false,
  --       symbol = false,
  --     },
  --     styles = {
  --       enabled = true,
  --       types = {},
  --       functions = {bold = true},
  --       parameters = {},
  --       comments = {italic = true},
  --       strings = {},
  --       keywords = {},
  --       variables = {},
  --       constants = {},
  --     },
  --     plugins = {
  --       treesitter = true,
  --       lspconfig = true,
  --       navic = true,
  --       cmp = true,
  --       indentblankline = true,
  --       neotree = true,
  --       nvimtree = true,
  --       whichkey = true,
  --       dashboard = true,
  --       gitsigns = true,
  --       telescope = true,
  --       noice = true,
  --       hop = true,
  --       ministatusline = true,
  --       minitabline = true,
  --       ministarter = true,
  --       minicursorword = true,
  --       notify = true,
  --       rainbowdelimiters = true,
  --       bufferline = true,
  --       lazy = true,
  --       rendermarkdown = true,
  --       ale = true,
  --       coc = true,
  --       leap = true,
  --       alpha = true,
  --       yanky = true,
  --       gitgutter = true,
  --       mason = true,
  --       flash = true,
  --     },
  --   },
  --   config = function(_, opts)
  --     vim.o.termguicolors = true
  --     vim.o.background = "dark"
  --     require("solarized").setup(opts)
  --     vim.cmd.colorscheme "solarized"
  --   end,
  -- },
}
